# secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: template
type: Opaque
data:
  # base64 encoded secrets
  MONGODB_URI: bW9uZ29kYjovL21vbmdvZGIudGVtcGxhdGU6MjcwMTcvbm90ZXM=
  PORT: MzAwMQ==
  SECRET: aGFzaGVyc2VjcmV0
