# secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: personalblog
type: Opaque
data:
  # base64 encoded secrets
  MONGODB_URI: mongodb://mongodb-service.personalblog:27017/personal_blog
  PORT: 3001
  SECRET: secretstring-base64-encoded
  ADMIN_EMAIL: admin@admin.com 
  ADMIN_PASSWORD: admin-pass-base64-encoded
