# secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: template
type: Opaque
data:
  # base64 encoded secrets
  MONGODB_URI: bW9uZ29kYjovL21vbmdvZGIudGVtcGxhdGU6MjcwMTcvbm90ZXM=
  POSTGRES_URI: cG9zdGdyZXM6Ly9teXVzZXI6bXlwYXNzd29yZEBwb3N0Z3Jlcy50ZW1wbGF0ZTo1NDMyL25vdGVz
  PORT: MzAwMQ==
  SECRET: aGFzaGVyc2VjcmV0
