apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: personalblog
  labels:
    app: frontend
spec:
  replicas: 1  # Adjust the number of replicas based on your load expectations
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: dpuertamartos/personalblog-frontend:latest
        ports:
        - containerPort: 5173  # Replace with the actual port your frontend listens on
