apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: personalblog
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: dpuertamartos/personalblog-backend:20240921084545-8f81f2d
        ports:
        - containerPort: 3001
        env:
        - name: MONGODB_URI
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: MONGODB_URI
        - name: PORT
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: PORT
        - name: SECRET
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: SECRET
        - name: ADMIN_EMAIL
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: ADMIN_EMAIL        
        - name: ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: ADMIN_PASSWORD
