apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: certbot-pvc
  namespace: template
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---      
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: certbot-var
  namespace: template
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: certbot-log
  namespace: template
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: webroot
  namespace: template
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi