apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-dev-config
  namespace: template
data:
  nginx.conf: |
    events { }
    http {
      server {
        listen 80;
        server_name localhost dev.local;

        location /health {
          return 200 'ok';
          add_header Content-Type text/plain;
        }

        location / {
          proxy_http_version 1.1;
          proxy_set_header Upgrade $http_upgrade;
          proxy_set_header Connection 'upgrade';
          proxy_pass http://frontend-service.template:5173;
        }

        location /api/ {
          proxy_http_version 1.1;
          proxy_set_header Upgrade $http_upgrade;
          proxy_set_header Connection 'upgrade';
          proxy_pass http://backend-service.template:3001;
        }
      }
    }
