apiVersion: v1
kind: Service
metadata:
  name: python-microservice-nodeport
  namespace: template  # replace with your actual namespace
spec:
  type: NodePort
  selector:
    app: python-microservice
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 32500  # This is the port that will be exposed on each node
