apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: template  # replace with your actual namespace
spec:
  type: NodePort
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
      nodePort: 32345  # This is the port that will be exposed on each node
