name: Deploy Frontend

on:
  push:
    branches:
      - master
    paths:
      - 'frontend/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.REPO_TOKEN }}  # Use the PAT token for checkout
        fetch-depth: 0
        
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      
    - name: Cache Docker layers
      uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-
          
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Generate tag
      run: echo "TAG=$(date +'%Y%m%d%H%M%S')-$(git rev-parse --short HEAD)" >> $GITHUB_ENV

    - name: Build and push Docker image with tag
      uses: docker/build-push-action@v2
      with:
        context: ./frontend
        file: ./frontend/Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/template-frontend:${{ env.TAG }}
        platforms: linux/amd64,linux/arm64
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache

    - name: Update Kubernetes YAML
      run: |
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git pull --ff-only 
        cat kubernetes/deploy-frontend.yaml
        sed -i 's|dpuertamartos/template-frontend:[^\"]*|dpuertamartos/template-frontend:${{ env.TAG }}|g' ./kubernetes/common/deploy-frontend.yaml
        cat kubernetes/deploy-frontend.yaml
        git add ./kubernetes/common/deploy-frontend.yaml
        git commit -m "Update frontend image tag to ${{ env.TAG }}"

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.REPO_TOKEN }}
        branch: 'master'  # Make sure to use the correct branch name

    - name: Deploy to Kubernetes
      uses: steebchen/kubectl@v2.0.0
      with:
        command: apply -f ./kubernetes/common/deploy-frontend.yaml
        config: ${{ secrets.KUBE_CONFIG_DATA_YOUR_KUBERNETES }}


