name: Build and Deploy python-microservice Service

on:
  push:
    branches:
      - master
    paths:
      - 'python_microservice/**'

jobs:
  build-and-push-python-microservice:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.REPO_TOKEN }}  # Use the PAT token for checkout
        fetch-depth: 0

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      
    - name: Cache Docker layers
      uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Generate tag for python-microservice
      run: echo "TAG=$(date +'%Y%m%d%H%M%S')-$(git rev-parse --short HEAD)" >> $GITHUB_ENV

    - name: Build and push Docker image for python-microservice
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./python_microservice/Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/template-python-microservice:${{ env.TAG }}
        platforms: linux/amd64,linux/arm64 
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache

    - name: Update Kubernetes YAML
      run: |
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git pull --ff-only 
        cat kubernetes/common/deploy-python-microservice.yaml
        sed -i 's|dpuertamartos/template-python-microservice:[^\"]*|dpuertamartos/template-python-microservice:${{ env.TAG }}|g' ./kubernetes/common/deploy-python-microservice.yaml
        cat kubernetes/common/deploy-python-microservice.yaml 
        git add ./kubernetes/common/deploy-python-microservice.yaml
        git commit -m "Update python-microservice image tag to ${{ env.TAG }}"
        
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.REPO_TOKEN }}
        branch: 'master'  

    - name: Deploy to Kubernetes
      uses: steebchen/kubectl@v2.0.0
      with:
        command: apply -f ./kubernetes/common/deploy-python-microservice.yaml
        config: ${{ secrets.KUBE_CONFIG_DATA_YOUR_KUBERNETES }}
